name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: ${{ !env.ACT }}
        with:
          command: manifest
    outputs:
      release_catwalk: ${{ steps.release.outputs['packages/catwalk--release_created'] || env.ACT }}

  upload-catwalk:
    name: Upload Catwalk for ${{ matrix.os }}
    needs: release-please
    runs-on: ${{ matrix.os }}
    if: ${{ needs.release-please.outputs.release_catwalk }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        member: ["catppuccin-catwalk"]
    env:
      EXECUTABLE: ${{ matrix.member }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: "Cache Cargo intermediate products"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}
      - run: |
          cargo build -r --locked -p ${{matrix.member}}
          cargo test -r --locked -p ${{matrix.member}}
      - name: Upload to release
        run: gh release upload "${{ steps.release.outputs['packages/catwalk--release_tag'] }}" "target/release/$EXECUTABLE"
